core/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name = "home"),
    path('blog/',include('blog.urls', namespace='blog')) #blog: y name de la url a la que quiero apuntar
]

core/views.py
from django.views.generic import View
from django.shortcuts import render, redirect, get_object_or_404

class HomeView(View):
    def get(self,request, *args, **kwargs):
        context={

        }
        return render(request,'index.html', context )

templates/blog_create.html
    <form name="" action="" method="POST">
        {% csrf_token %}
        Title: {{form.title}} 
    <br>
        content: {{form.content}}
    <button type="submit">Submit</button>
    </form>

templates/blog_delete.html
   
   Are you sure?
   <form name="" action="" method="POST">
        {% csrf_token %}
    {{form}} 
    <br>
    <button type="submit">Delete</button>
    </form>

templates/blog_detail.html
{{post.title}}
<br>
{{post.content}}
<br>

templates/blog_list.html
Blog list
<br>
{% for post in posts%}<!-- por cada post mostrar titulo y opciones dde update y delete-->

<a href=" {% url 'blog:detail' post.id %} ">{{post.title}}</a>
<a href=" {% url 'blog:update' post.id %} ">Update</a> 
<a href=" {% url 'blog:delete' post.id %} ">Delete</a>

{% endfor %}
<br>
<a href="{% url 'blog:create' %}">Create</a>

templates/blog_update.html
    <form name="" action="" method="POST">
        {% csrf_token %}
        Title: {{form.title}} 
    <br>
        content: {{form.content}}
    <button type="submit">Update</button>
    </form>

templates/index.html
    Hola, visita mi <a href="{% url 'blog:home' %}"> blog aquí </a>